name : CI pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
  steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setup docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build user Service
      run: |
        docker build -t user-service:latest ./user-service

    - name: Build product-service
      run: docker build -t product-service:latest ./product-service

    - name: Build order-service
      run: docker build -t order-service:latesst ./order-service

    - name: Build Recommend Service
      run: docker build -t recommend-service:latest ./recommend-service

    - name: Run Docker Compose
      run: docker-compose -f docker-compose.yml up -d

    - name: Test User Service
      run: |
        sleep 10
        curl --fail http://localhost:8080/users

    - name: Test Product Service
      run: |
        curl --fail http://localhost:3000/products

    - name: Test Order Service
      run: |
        curl --fail -X POST -H "Content-Type: application/json" -d '{"user_id": 1, "product_id": 101}' http://localhost:5000/orders

    - name: Test Recommend Service
      run: |
        curl --fail http://localhost:8081/recommend

    - name: Clean up
      run: |
        docker-compose down
